### ISSUE TITLE
Here app support for bike-navigation device

### ISSUE THREAD

**Issue by puusor** [heremaps/bike-navigation#13]
Hello,

Does the regular Here map app (that is available in google store) support bike-navigation device or are you using a custom app developed with Here API?

Additionally, if the Here app directly supports bike-navigation app, does it also support any BT device that exposes the BikeNavi BLE profile? 

If a custom app (developed using Here SDK) is needed, have you made the source for it public somewhere?

**Comment by dgrafov** [comment]
According to: https://360.here.com/2015/11/12/head-home-faster-with-the-latest-here-for-android/ the app in GooglePlay supports it. I didn't hear anything about AppStore release supporting bike-navigation. 
There is mobile SDK (https://developer.here.com/documentation) for a custom app, but it has 90 days trial only.

**Comment by puusor** [comment]
thanks for the quick reply!
