### ISSUE TITLE
Can't open board/BikeNavigation.brd

### ISSUE THREAD

**Issue by dwlocks** [heremaps/bike-navigation#2]
I tried uploading board/BikeNavigation.brd to oshpark.com and got  "Failed: Invalid or corrupt "brd" file".

I tried opening BikeNavigation.brd in linux 64bit eagle 7.4.0 and get this:  "Error:  line 2542, column 10: redefinition of name 'IC1' in tag <element>"

This is my first time using Eagle, so I'm afraid I didn't look any deeper than this.

**Comment by eugmes** [comment]
Thanks for your report. I fixed the wrong reference, now the board can be uploaded to OSH Park. We didn't try to produce it on OSH Park, it would be interesting to know how it worked.
